willfulbard/larkcamp_reg

public/config.json

Definition of done for this PR is whether we can create the CSV after this form is filled out (minus price total). We can fix form ergonomics and make edits to this years' registration procedure in subsequent PRs.
*[ Camper Info  ]*
*[ 5 more copies of the above Camper info cols ]*

Rough, data-complete schema for form

---

.gitignore
README.md
composer.json
composer.lock
create.sql
package.json
php-tests/RegTest.php
php-tests/fakesendmail.sh
phpunit.xml
public/register.php

Hey,
Sorry I've been unable to look at this for a while.  I'm still dealing with some things from the big board meeting last weekend.  This still needs some work, but it's at least a start.
--Will

Create basic backend

---

package.json
src/App.tsx
src/appTypes.ts

I added in a few app states that it would probably be good to have. I also made it so that submitting the form actually functions.
Also I modified local php script to bind to 0.0.0.0 because proxy wasn't working w/o that. Let me know if you got proxying to work without that, or otherwise don't want this in head.

Add in a few app states, make submission work.

---

public/config.json

Edit config for dependent fields (and also some slight reordering of fields)

---

package.json
php-tests/RegTest.php
php-tests/generate-random-reg.js
public/JSON.php
public/Mailer.php
public/register.php
yarn.lock

This does the following:
- Moves mailer and JSON to a separate class since these will probably be used for the click-wrap agreements for instructors.
- Adds json-schema-faker to use to create random data from the schema
- Adds json schema validation and creates random data for the tests based on the schema

Implement schema validation

---

package.json
public/config.json
src/App.tsx
src/appTypes.ts
src/json-logic-js.d.ts
yarn.lock

App.jsx ain't looking super pretty at this point, but I'll clean it up in subsequent PRs

add in barebones pricing logic

---

public/config.json

This PR implements the pricing logic in the world where discount by payment type doesn't exist.
Closer and closer!

Implement pricing (without discount)

---

public/config.json

Add in some small UX improvements, such as properly named fields, a textarea for comments, and other misc changes. 
The form is looking nicer and nicer!!

Add in some small UX improvements 

---

public/config.json

This PR adds in the discount Lark pricing to the pricing logic. This should mean that the pricing function is correct at this point, however, we'll probably want to write some quick tests to verify this.
Go us!

Add discount to pricing logic

---

public/config.json
src/components/App/App.css
src/components/PriceTicker/PriceTicker.css
src/components/Spinner/Spinner.css
src/components/Spinner/Spinner.tsx
src/index.css

Green background, small bits of padding, other small visual tweaks.
Hopefully this makes it look and feel a bit nicer!

Small styling improvements

---

src/components/App/App.css
src/index.css

This comes from the palette!
Notes:
- We probs want to do some variety of css defns + imports, but I haven't looked at that at all.
- We ALSO might want in the far future to have this be customizable per camp, in the same way that the layout is!

switch to using better green for background

---

.env-travis
.travis.yml
create.sql
php-tests/RegTest.php
php-tests/fakesendmail.sh
public/config.json
public/php/DBConn.php
public/php/Env.php
public/php/Mailer.php
public/register.php

This adds travis-ci integration into the project.  There were a couple other changes I had to make to get this working:
- I changed number to integer in the schema, since floating-point errors were making the tests rather fragile.
- I changed the `autoincrement` to `auto_increment` (mysql)
- Move the `.env` parsing into a separate module
closes #28

Add travis integration

---

package.json
php-tests/RegTest.php
public/config.json
public/php/DBConn.php
public/php/Env.php
public/php/Payload.php
public/register.php
src/components/App/App.css
src/components/App/App.tsx
tsconfig.json
types/react-phone-number-input/index.d.ts
yarn.lock

I noticed that the phone number input still had a little fragility.  This fixes that by:
- Adding a custom phone input which allows us to normalize the phone input
- Changing the `payer_number` input validation to something simpler
- Adding a special test that just runs through random input 50 times to act as a better safe-guard against intermittent schema failures.

Fix phone number fragility

---

public/config.json
src/components/App/App.tsx
src/components/NaturalNumberInput/index.tsx

A replacement for #32, tackles #31

Make inputs not except non-naturals for donation and t-shirt boxes

---

public/config.json
src/components/App/App.css
src/components/App/App.tsx

Edit text, shirt pricing, remove Woodlands donation

---

public/config.json
src/__tests__/config.test.js

according to Celia's 10/31 edits

Update text and meal prices

---

package.json
php-tests/RegPayloadTest.php
php-tests/RegTest.php
php-tests/fakesendmail.sh
php-tests/read-test-email.js
public/php/RegValueFormatter.php
public/register.php
yarn.lock

Will finish csv

---

.gitignore
json-to-csv.json
package.json
php-tests/RegPayloadTest.php
php-tests/RegTest.php
public/.htaccess
public/config.json
public/php/RegPayload.php
public/php/RegValueFormatter.php
public/register.php
src/components/App/App.tsx
src/components/App/appTypes.ts

Lots of little problems/improvements.  See commit messages.

Will misc fixes

---

src/components/App/App.tsx
src/components/utils.ts

pricing ticker was an update behind, don't know exactly why but putting calculate price in rerender fixed it. amusingly this is a performance win bc setstate is called once per update now.

fix pricing ticker

---

src/components/utils.ts

Fixes first part of #54 
lots of whitespace changes, sorry!

allow removing all campers without crashing

---

src/components/App/App.tsx

Fix pricing disappear on adding a camper
